In [1]:
import numpy as np

In [5]:
#create 1D array
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
#create 2D array
b=np.array([[1,2,4],[4,5,6],[7,8,9]])
print(b)

[[1 2 4]
 [4 5 6]
 [7 8 9]]


In [9]:
#creae zeros
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
